# This is a basic workflow to help you get started with Actions
name: Build and Deploy Spring Boot to AWS EC2   #액션의 이름을 설정

on:
  push:
    branches: [ master ]              #해당브랜치가 push될때 해당 액션을 실행한다.

jobs:               #실제수행내용
  build:
    runs-on: ubuntu-18.04                  #액션을 실행시키는 Runner의 운영체제
    steps:                                #실제 수행내용 단계별로 name과 수행동작을 적어둔다
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Java JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash
      
      - name: Build with Gradle
        run: ./gradlew build
        shell: bash
